platform :ios, '9.0'
use_frameworks!

target 'RectangleScanner_Example' do
  pod 'RectangleScanner', :path => '../'
  pod 'GPUImage'

  target 'RectangleScanner_Tests' do
    inherit! :search_paths

    
  end
end
